### PR TITLE
PR: Update to `Node.js v20` #85

### PR DESCRIPTION
**Pull request by nelsonic**
This is a much-needed update to:
+ [x] Latest AWS SDK (v3) 🎉 
+ [x] Node.js v20 LTS

So that we can continue deploying Lambda Functions for the next couple of years.

Also:
+ [x] Replace [Travis CI](https://github.com/dwyl/learn-travis/issues/67) with GitHub Actions CI.

### CODE REVIEW

**Comment by nelsonic** [comment]
`process.env.TMPDIR` not defined:
https://github.com/dwyl/aws-lambda-deploy/actions/runs/7627531669/job/20776434794#step:6:21
image

Added it to:  https://github.com/dwyl/aws-lambda-deploy/settings/secrets/actions
TMPDIR-secret-added

Gonna re-run the build ...

**Comment by nelsonic** [comment]
Gonna have to come back to this ... debugging GitHub CI is super tedious ... 🙄

**Comment by nelsonic** [comment]
This is such a time-suck. I would gladly pay someone `else` $100 to make this go away.

**Comment by nelsonic** [comment]
`Error: ENOENT: no such file or directory, scandir '/home/runner/work/_temp/fakedir'`
https://github.com/dwyl/aws-lambda-deploy/actions/runs/7643215698/job/20824696029#step:6:33

image

I think this is a "New Node" throwing an error where it didn't before ... 💭

**Comment by nelsonic** [comment]
Tests fail because function already exists:
https://github.com/dwyl/aws-lambda-deploy/actions/runs/7767852616/job/21185130555#step:6:81
image

Think I'm going to side-step this issue by only testing on _one_ version of `Node.js`
Simply because running the test on 3 different instances is almost guaranteed to cause conflicts. 🙄

**Comment by nelsonic** [comment]
Tests passing. Going to try to re-enable the `Node.js` matrix (to test with various versions). 🤞

**Comment by nelsonic** [comment]
Nope. Race condition when running the tests in parallel. 🙄 
Might check if we can run them in series ...

**Comment by nelsonic** [comment]
OK. I'm at the point where I'm "happy" with this. Going to bump the version and publish. 📦

**Review by asntc — APPROVED** [review]
Nice! 👌

**Pull request merged**
