### PR TITLE
use path.resolve for file operations to ensure cross-platform compatibility

### PR DESCRIPTION
**Pull request by nelsonic**
fix "broken" utils tests. #52

### CODE REVIEW

**Comment by nelsonic** [comment]
@jackcarlisle can you please check/merge this PR. thanks!

**Comment by jackcarlisle** [comment]
👍 looks good to me!

**Comment by lennym** [comment]
Just looking at 0a391ed I'd recommend always using `path.resolve` or path.join` in favour of string concatenation to join file paths. That way you never need to worry about whether things are defined with trailing slashes or not. `path.normalise(x + y)` is not equivalent because it depends on trailing/leading slashes on `x` and `y` respectively.

```javascript
path.join('foo/', 'bar'); // => 'foo/bar'
path.join('foo', 'bar'); // => 'foo/bar'
path.join('foo///', 'bar'); // => 'foo/bar'
```

**Comment by lennym** [comment]
Further "path" advice, that's less pertinent here: use `path.resolve` to turn a relative path into an absolute one as early as possible in your pipeline. Passing a relative path around can change what the relative path is relative to, and therefore can have unexpected results.

**Pull request merged**
