### PR TITLE
PR: Update to `Node v20` issue #85

### PR DESCRIPTION
**Pull request by nelsonic**
Busy updating this so that I can deploy a new lambda function ... 🧑‍💻 ⏳

### CODE REVIEW

**Comment by nelsonic** [comment]
Getting the following lines not covered by tests: 

image

😕

**Comment by nelsonic** [comment]
Also: 

```sh
> nyc tape ./test/*.test.js | tap-nyc

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    | process.env.TMPDIR: /Users/n/code/aws-lambda-deploy/tmp/
    | where dpl will temporarily store the Lambda Function zip file.
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(node:15914) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
```

**Comment by nelsonic** [comment]
On `localhost` I get:

```
    =============================== Coverage summary ===============================
    Statements   : 100% ( 142/142 )
    Branches     : 100% ( 30/30 )
    Functions    : 100% ( 27/27 )
    Lines        : 100% ( 141/141 )
    ================================================================================

  total:     41
  passing:   41

  duration:  2m 41.6s
```

I've added the `.env` vars to GitHub: https://github.com/dwyl/aws-lambda-deploy/settings/secrets/actions

**Comment by nelsonic** [comment]
I think this needs to be merged into `main` for the GitHub Actions to start working ... 💭

**Review by asntc — APPROVED** [review]
LGTM. 👌

**Pull request merged**
